
seed: 0
device: cuda:0
optimizer: ADAM # ADAM, GN 
visualize: True

data: 
  gt_sdf_file: gt_sdfs/035_power_drill.npy
  sdf_transf_file: gt_sdfs/035_power_drill_transform.txt
  scene_file: gt_sdfs/nontextured.stl

camera:
  depth_scale: 1.0
  cam_dist: 0.0
  intrinsics:
    w: 1280
    h: 720
    yfov: 60

  noise: 
    rotation: 0.2
    translation: 1e-2

sampling: 
  n_rays: 200
  n_strat_samples: 0
  n_surf_samples: 100
  depth_range: [0.3, 1.0]   # [0.6, 6.0] for D455, [0.3, 3.0] for D435
  surface_samples_offset: 0.01
  dist_behind_surf: 0.1

loss:
  bounds_method: pc
  loss_type: L1
  trunc_weight: 25.0
  eik_weight: 0.0
  trunc_distance: 5e-2